# Generated by Django 3.2.25 on 2025-05-23 02:21

import applications.academic_procedures.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_procedures', '0015_committeemember_publicationcount_seminarcomment_seminarconsent_seminarentry_thesistopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('synopsis', models.FileField(upload_to=applications.academic_procedures.models.upload_synopsis)),
                ('thesis_report', models.FileField(upload_to=applications.academic_procedures.models.upload_report)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('director_approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('supervisor_pending', 'Pending with Supervisor'), ('hod_pending', 'Approved by Supervisor, Pending with HOD'), ('hod_rejected', 'Rejected by HOD, Returned to Supervisor'), ('dean_pending', 'Approved by HOD, Pending with Dean'), ('dean_rejected', 'Rejected by Dean, Returned to HOD'), ('dean_approved', 'Approved by Dean')], default='submitted', max_length=30)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_subs', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_subs', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='academic_procedures.thesistopic')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=255)),
                ('prof_position', models.CharField(max_length=255)),
                ('prof_address', models.TextField()),
                ('prof_phone', models.CharField(max_length=20)),
                ('prof_email', models.EmailField(max_length=254)),
                ('prof_time_ranking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('review_form_sent', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_procedures.thesissubmission')),
            ],
            options={
                'unique_together': {('submission', 'priority')},
            },
        ),
    ]
